sass:
  sass_dir: css/sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot

languages: ['en', 'ru']
default_lang: 'en'
exclude_from_localization: ['clips', 'css', 'files', 'font', 'font-awesome', 'fonts', 'img', 'js']
parallel_localization: true