collections:
  posts:
    output: true
  terms:
    output: true

image: AB_facebook_OG_Crowdsale.png


excerpt_separator: <!--more-->

sass:
  sass_dir: css/sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot

permalink: /:title

languages: ['en', 'ru']
default_lang: 'en'
exclude_from_localization: ['clips', 'css', 'files', 'font', 'font-awesome', 'fonts', 'img', 'js']
parallel_localization: true