collections:
  posts:
    output: true
  terms:
    output: true

title: Acebusters - Poker on the Ethereum blockchain
description: Join Acebusters now! The decentralized economy to make online poker profitable, fair and secure. Poker on the Ethereum blockchain. Ace or bust!
image: AB_facebook_OG_Crowdsale.png


excerpt_separator: <!--more-->

sass:
  sass_dir: css/sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-assets
  - jekyll-timeago

permalink: /:title

assets:
  digest: false

languages: ['en', 'ru']
default_lang: 'en'
exclude_from_localization: ['clips', 'css', 'files', 'font', 'font-awesome', 'fonts', 'img', 'js']
parallel_localization: true
exclude: ['scripts']
